// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;



class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdSnPY7e4rFGF2GeBn2FesIZrfNvT23rQ',
    appId: '1:641680704983:web:a3a06d4d61e010c946b792',
    messagingSenderId: '641680704983',
    projectId: 'virtual-beauty-tryon-17f90',
    authDomain: 'virtual-beauty-tryon-17f90.firebaseapp.com',
    storageBucket: 'virtual-beauty-tryon-17f90.firebasestorage.app',
    measurementId: 'G-M4MDQ1JQ60',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6gnbfONL6LdG7eUqVdK5EGRNdLkQkAuI',
    appId: '1:641680704983:android:f6136da09d64e88046b792',
    messagingSenderId: '641680704983',
    projectId: 'virtual-beauty-tryon-17f90',
    storageBucket: 'virtual-beauty-tryon-17f90.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA476i3Yog8jeVgPyKSdNBnlCIy276u66w',
    appId: '1:641680704983:ios:70fc405cae269b7a46b792',
    messagingSenderId: '641680704983',
    projectId: 'virtual-beauty-tryon-17f90',
    storageBucket: 'virtual-beauty-tryon-17f90.firebasestorage.app',
    iosBundleId: 'com.example.beautyArMarketplace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA476i3Yog8jeVgPyKSdNBnlCIy276u66w',
    appId: '1:641680704983:ios:70fc405cae269b7a46b792',
    messagingSenderId: '641680704983',
    projectId: 'virtual-beauty-tryon-17f90',
    storageBucket: 'virtual-beauty-tryon-17f90.firebasestorage.app',
    iosBundleId: 'com.example.beautyArMarketplace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdSnPY7e4rFGF2GeBn2FesIZrfNvT23rQ',
    appId: '1:641680704983:web:167e216dbc7509c546b792',
    messagingSenderId: '641680704983',
    projectId: 'virtual-beauty-tryon-17f90',
    authDomain: 'virtual-beauty-tryon-17f90.firebaseapp.com',
    storageBucket: 'virtual-beauty-tryon-17f90.firebasestorage.app',
    measurementId: 'G-XKWTFZK933',
  );
}
